version: "3.8"

services:
  app:
    build: .
    container_name: dino-wallet-service
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_A0KjBQdC2WJD@ep-round-cherry-aif68pw1-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
